"""alterando banco

Revision ID: 4861474447f0
Revises: cfa2066dd3b9
Create Date: 2025-10-11 09:41:01.048266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4861474447f0'
down_revision = 'cfa2066dd3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_motoristas', schema=None) as batch_op:
        batch_op.alter_column('motorista_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('documentos_veiculos', schema=None) as batch_op:
        batch_op.alter_column('veiculo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_veiculos', schema=None) as batch_op:
        batch_op.alter_column('veiculo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('documentos_motoristas', schema=None) as batch_op:
        batch_op.alter_column('motorista_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
