"""adicao do botao de ativar /desativar tranportador

Revision ID: 63e752e421f5
Revises: 
Create Date: 2025-10-14 14:52:06.734743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e752e421f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=120), nullable=False),
    sa.Column('prazo_alerta_dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_documento')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('razao_social')
    )
    op.create_table('documentos_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=120), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome_documento', name='_empresa_docfiscal_uc')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('operacao', sa.String(length=120), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('operacao', sa.String(length=120), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('documentos_motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=120), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motorista_id', 'nome_documento', name='_motorista_documento_uc')
    )
    op.create_table('documentos_veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=120), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('veiculo_id', 'nome_documento', name='_veiculo_documento_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_veiculos')
    op.drop_table('documentos_motoristas')
    op.drop_table('veiculos')
    op.drop_table('usuarios')
    op.drop_table('motoristas')
    op.drop_table('documentos_fiscais')
    op.drop_table('empresas')
    op.drop_table('configuracoes_alertas')
    # ### end Alembic commands ###
