"""Remove nome fantasia

Revision ID: 6b8dc1ac0eae
Revises: fb7ddd8016d2
Create Date: 2025-10-10 15:23:59.939611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8dc1ac0eae'
down_revision = 'fb7ddd8016d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('nome_fantasia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_fantasia', sa.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
