"""Remove tabela convites

Revision ID: fb7ddd8016d2
Revises: 
Create Date: 2025-10-10 15:00:57.554228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7ddd8016d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=120), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome_documento', name='_empresa_docfiscal_uc')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('operacao', sa.String(length=120), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('operacao', sa.String(length=120), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('documentos_motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=120), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motorista_id', 'nome_documento', name='_motorista_documento_uc')
    )
    op.create_table('documentos_veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=120), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('veiculo_id', 'nome_documento', name='_veiculo_documento_uc')
    )
    op.drop_table('transportadores')
    op.drop_table('documentos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_documento', sa.VARCHAR(length=120), nullable=False),
    sa.Column('data_vencimento', sa.DATE(), nullable=False),
    sa.Column('transportador_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['transportador_id'], ['transportadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transportador_id', 'nome_documento', name=op.f('_transportador_documento_uc'))
    )
    op.create_table('transportadores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cnh', sa.VARCHAR(length=20), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh'),
    sa.UniqueConstraint('nome')
    )
    op.drop_table('documentos_veiculos')
    op.drop_table('documentos_motoristas')
    op.drop_table('veiculos')
    op.drop_table('motoristas')
    op.drop_table('documentos_fiscais')
    # ### end Alembic commands ###
